# Form implementation generated from reading ui file 'add_connection.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_d_addConnectionWindow(object):
    def setupUi(self, d_addConnectionWindow):
        d_addConnectionWindow.setObjectName("d_addConnectionWindow")
        d_addConnectionWindow.resize(842, 502)
        self.label = QtWidgets.QLabel(parent=d_addConnectionWindow)
        self.label.setGeometry(QtCore.QRect(580, 190, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.le_bitCount = QtWidgets.QLineEdit(parent=d_addConnectionWindow)
        self.le_bitCount.setGeometry(QtCore.QRect(580, 220, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_bitCount.setFont(font)
        self.le_bitCount.setObjectName("le_bitCount")
        self.label_2 = QtWidgets.QLabel(parent=d_addConnectionWindow)
        self.label_2.setGeometry(QtCore.QRect(780, 230, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.tv_connectionList = QtWidgets.QTableWidget(parent=d_addConnectionWindow)
        self.tv_connectionList.setGeometry(QtCore.QRect(0, 0, 571, 511))
        self.tv_connectionList.setObjectName("tv_connectionList")
        self.tv_connectionList.setColumnCount(0)
        self.tv_connectionList.setRowCount(0)

        self.retranslateUi(d_addConnectionWindow)
        QtCore.QMetaObject.connectSlotsByName(d_addConnectionWindow)

    def retranslateUi(self, d_addConnectionWindow):
        _translate = QtCore.QCoreApplication.translate
        d_addConnectionWindow.setWindowTitle(_translate("d_addConnectionWindow", "Dialog"))
        self.label.setText(_translate("d_addConnectionWindow", "Пропускная способность:"))
        self.label_2.setText(_translate("d_addConnectionWindow", "бит/с"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    d_addConnectionWindow = QtWidgets.QDialog()
    ui = Ui_d_addConnectionWindow()
    ui.setupUi(d_addConnectionWindow)
    d_addConnectionWindow.show()
    sys.exit(app.exec())
