# Form implementation generated from reading ui file 'add_node.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_d_addNodeWindow(object):
    def setupUi(self, d_addNodeWindow):
        d_addNodeWindow.setObjectName("d_addNodeWindow")
        d_addNodeWindow.resize(720, 382)
        self.tv_nodeList = QtWidgets.QTableView(parent=d_addNodeWindow)
        self.tv_nodeList.setGeometry(QtCore.QRect(0, 0, 441, 381))
        self.tv_nodeList.setObjectName("tv_nodeList")
        self.l_nodeName = QtWidgets.QLabel(parent=d_addNodeWindow)
        self.l_nodeName.setGeometry(QtCore.QRect(450, 10, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l_nodeName.setFont(font)
        self.l_nodeName.setObjectName("l_nodeName")
        self.le_nodeName = QtWidgets.QLineEdit(parent=d_addNodeWindow)
        self.le_nodeName.setGeometry(QtCore.QRect(450, 40, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_nodeName.setFont(font)
        self.le_nodeName.setObjectName("le_nodeName")
        self.l_x = QtWidgets.QLabel(parent=d_addNodeWindow)
        self.l_x.setGeometry(QtCore.QRect(450, 90, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l_x.setFont(font)
        self.l_x.setObjectName("l_x")
        self.le_x = QtWidgets.QLineEdit(parent=d_addNodeWindow)
        self.le_x.setGeometry(QtCore.QRect(560, 90, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_x.setFont(font)
        self.le_x.setObjectName("le_x")
        self.l_y = QtWidgets.QLabel(parent=d_addNodeWindow)
        self.l_y.setGeometry(QtCore.QRect(450, 120, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l_y.setFont(font)
        self.l_y.setObjectName("l_y")
        self.le_y = QtWidgets.QLineEdit(parent=d_addNodeWindow)
        self.le_y.setGeometry(QtCore.QRect(560, 120, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_y.setFont(font)
        self.le_y.setObjectName("le_y")
        self.pb_addNode = QtWidgets.QPushButton(parent=d_addNodeWindow)
        self.pb_addNode.setGeometry(QtCore.QRect(604, 322, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_addNode.setFont(font)
        self.pb_addNode.setObjectName("pb_addNode")

        self.retranslateUi(d_addNodeWindow)
        QtCore.QMetaObject.connectSlotsByName(d_addNodeWindow)

    def retranslateUi(self, d_addNodeWindow):
        _translate = QtCore.QCoreApplication.translate
        d_addNodeWindow.setWindowTitle(_translate("d_addNodeWindow", "Dialog"))
        self.l_nodeName.setText(_translate("d_addNodeWindow", "Название узла:"))
        self.l_x.setText(_translate("d_addNodeWindow", "Координата X:"))
        self.l_y.setText(_translate("d_addNodeWindow", "Координата Y:"))
        self.pb_addNode.setText(_translate("d_addNodeWindow", "Добавить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    d_addNodeWindow = QtWidgets.QDialog()
    ui = Ui_d_addNodeWindow()
    ui.setupUi(d_addNodeWindow)
    d_addNodeWindow.show()
    sys.exit(app.exec())
