# Form implementation generated from reading ui file 'change_node.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_d_changeNodeWindow(object):
    def setupUi(self, d_changeNodeWindow):
        d_changeNodeWindow.setObjectName("d_changeNodeWindow")
        d_changeNodeWindow.resize(722, 354)
        self.tv_nodeList = QtWidgets.QTableView(parent=d_changeNodeWindow)
        self.tv_nodeList.setGeometry(QtCore.QRect(0, 0, 441, 351))
        self.tv_nodeList.setObjectName("tv_nodeList")
        self.l_y_2 = QtWidgets.QLabel(parent=d_changeNodeWindow)
        self.l_y_2.setGeometry(QtCore.QRect(450, 130, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l_y_2.setFont(font)
        self.l_y_2.setObjectName("l_y_2")
        self.le_newY = QtWidgets.QLineEdit(parent=d_changeNodeWindow)
        self.le_newY.setGeometry(QtCore.QRect(560, 130, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_newY.setFont(font)
        self.le_newY.setObjectName("le_newY")
        self.l_x_2 = QtWidgets.QLabel(parent=d_changeNodeWindow)
        self.l_x_2.setGeometry(QtCore.QRect(450, 100, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l_x_2.setFont(font)
        self.l_x_2.setObjectName("l_x_2")
        self.le_newNodeName = QtWidgets.QLineEdit(parent=d_changeNodeWindow)
        self.le_newNodeName.setGeometry(QtCore.QRect(450, 50, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_newNodeName.setFont(font)
        self.le_newNodeName.setObjectName("le_newNodeName")
        self.l_nodeName_2 = QtWidgets.QLabel(parent=d_changeNodeWindow)
        self.l_nodeName_2.setGeometry(QtCore.QRect(450, 20, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l_nodeName_2.setFont(font)
        self.l_nodeName_2.setObjectName("l_nodeName_2")
        self.le_newX = QtWidgets.QLineEdit(parent=d_changeNodeWindow)
        self.le_newX.setGeometry(QtCore.QRect(560, 100, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_newX.setFont(font)
        self.le_newX.setObjectName("le_newX")
        self.pb_changeNode = QtWidgets.QPushButton(parent=d_changeNodeWindow)
        self.pb_changeNode.setGeometry(QtCore.QRect(600, 300, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_changeNode.setFont(font)
        self.pb_changeNode.setObjectName("pb_changeNode")

        self.retranslateUi(d_changeNodeWindow)
        QtCore.QMetaObject.connectSlotsByName(d_changeNodeWindow)

    def retranslateUi(self, d_changeNodeWindow):
        _translate = QtCore.QCoreApplication.translate
        d_changeNodeWindow.setWindowTitle(_translate("d_changeNodeWindow", "Dialog"))
        self.l_y_2.setText(_translate("d_changeNodeWindow", "Координата Y:"))
        self.l_x_2.setText(_translate("d_changeNodeWindow", "Координата X:"))
        self.l_nodeName_2.setText(_translate("d_changeNodeWindow", "Название узла:"))
        self.pb_changeNode.setText(_translate("d_changeNodeWindow", "Изменить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    d_changeNodeWindow = QtWidgets.QDialog()
    ui = Ui_d_changeNodeWindow()
    ui.setupUi(d_changeNodeWindow)
    d_changeNodeWindow.show()
    sys.exit(app.exec())
