# Form implementation generated from reading ui file 'delete_node.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_d_deleteNodeWindow(object):
    def setupUi(self, d_deleteNodeWindow):
        d_deleteNodeWindow.setObjectName("d_deleteNodeWindow")
        d_deleteNodeWindow.resize(615, 343)
        self.tv_nodeList = QtWidgets.QTableView(parent=d_deleteNodeWindow)
        self.tv_nodeList.setGeometry(QtCore.QRect(0, 0, 441, 351))
        self.tv_nodeList.setObjectName("tv_nodeList")
        self.pb_deleteNode = QtWidgets.QPushButton(parent=d_deleteNodeWindow)
        self.pb_deleteNode.setGeometry(QtCore.QRect(490, 290, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_deleteNode.setFont(font)
        self.pb_deleteNode.setObjectName("pb_deleteNode")

        self.retranslateUi(d_deleteNodeWindow)
        QtCore.QMetaObject.connectSlotsByName(d_deleteNodeWindow)

    def retranslateUi(self, d_deleteNodeWindow):
        _translate = QtCore.QCoreApplication.translate
        d_deleteNodeWindow.setWindowTitle(_translate("d_deleteNodeWindow", "Dialog"))
        self.pb_deleteNode.setText(_translate("d_deleteNodeWindow", "Удалить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    d_deleteNodeWindow = QtWidgets.QDialog()
    ui = Ui_d_deleteNodeWindow()
    ui.setupUi(d_deleteNodeWindow)
    d_deleteNodeWindow.show()
    sys.exit(app.exec())
