# Form implementation generated from reading ui file 'load_matrix.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_d_loadMatrixWindow(object):
    def setupUi(self, d_loadMatrixWindow):
        d_loadMatrixWindow.setObjectName("d_loadMatrixWindow")
        d_loadMatrixWindow.resize(643, 593)
        self.tw_loadMatrix = QtWidgets.QTableWidget(parent=d_loadMatrixWindow)
        self.tw_loadMatrix.setGeometry(QtCore.QRect(0, 0, 651, 601))
        self.tw_loadMatrix.setObjectName("tw_loadMatrix")
        self.tw_loadMatrix.setColumnCount(0)
        self.tw_loadMatrix.setRowCount(0)

        self.retranslateUi(d_loadMatrixWindow)
        QtCore.QMetaObject.connectSlotsByName(d_loadMatrixWindow)

    def retranslateUi(self, d_loadMatrixWindow):
        _translate = QtCore.QCoreApplication.translate
        d_loadMatrixWindow.setWindowTitle(_translate("d_loadMatrixWindow", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    d_loadMatrixWindow = QtWidgets.QDialog()
    ui = Ui_d_loadMatrixWindow()
    ui.setupUi(d_loadMatrixWindow)
    d_loadMatrixWindow.show()
    sys.exit(app.exec())
