# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_mw_mainWindow(object):
    def setupUi(self, mw_mainWindow):
        mw_mainWindow.setObjectName("mw_mainWindow")
        mw_mainWindow.resize(1260, 732)
        self.centralwidget = QtWidgets.QWidget(parent=mw_mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gv_field = QtWidgets.QGraphicsView(parent=self.centralwidget)
        self.gv_field.setGeometry(QtCore.QRect(0, 121, 1261, 581))
        self.gv_field.setObjectName("gv_field")
        self.gb_node = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.gb_node.setGeometry(QtCore.QRect(0, 0, 201, 111))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gb_node.setFont(font)
        self.gb_node.setObjectName("gb_node")
        self.pb_main_addNode = QtWidgets.QPushButton(parent=self.gb_node)
        self.pb_main_addNode.setGeometry(QtCore.QRect(0, 20, 201, 31))
        self.pb_main_addNode.setObjectName("pb_main_addNode")
        self.pb_main_changeNode = QtWidgets.QPushButton(parent=self.gb_node)
        self.pb_main_changeNode.setGeometry(QtCore.QRect(0, 50, 201, 31))
        self.pb_main_changeNode.setObjectName("pb_main_changeNode")
        self.pb_main_deleteNode = QtWidgets.QPushButton(parent=self.gb_node)
        self.pb_main_deleteNode.setGeometry(QtCore.QRect(0, 80, 201, 31))
        self.pb_main_deleteNode.setObjectName("pb_main_deleteNode")
        self.gb_connection = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.gb_connection.setGeometry(QtCore.QRect(240, 0, 201, 111))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gb_connection.setFont(font)
        self.gb_connection.setObjectName("gb_connection")
        self.pb_main_addConnection = QtWidgets.QPushButton(parent=self.gb_connection)
        self.pb_main_addConnection.setGeometry(QtCore.QRect(0, 30, 201, 71))
        self.pb_main_addConnection.setObjectName("pb_main_addConnection")
        self.gb_matrix = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.gb_matrix.setGeometry(QtCore.QRect(480, 0, 411, 111))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gb_matrix.setFont(font)
        self.gb_matrix.setObjectName("gb_matrix")
        self.pb_main_adjacencyMatrix = QtWidgets.QPushButton(parent=self.gb_matrix)
        self.pb_main_adjacencyMatrix.setGeometry(QtCore.QRect(0, 30, 201, 31))
        self.pb_main_adjacencyMatrix.setObjectName("pb_main_adjacencyMatrix")
        self.pb_main_incidenceMatrix = QtWidgets.QPushButton(parent=self.gb_matrix)
        self.pb_main_incidenceMatrix.setGeometry(QtCore.QRect(0, 70, 201, 31))
        self.pb_main_incidenceMatrix.setObjectName("pb_main_incidenceMatrix")
        self.pb_main_loadMatrix = QtWidgets.QPushButton(parent=self.gb_matrix)
        self.pb_main_loadMatrix.setGeometry(QtCore.QRect(220, 30, 191, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_main_loadMatrix.setFont(font)
        self.pb_main_loadMatrix.setObjectName("pb_main_loadMatrix")
        self.pb_shortestPath = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pb_shortestPath.setGeometry(QtCore.QRect(1060, 30, 181, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_shortestPath.setFont(font)
        self.pb_shortestPath.setObjectName("pb_shortestPath")
        mw_mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=mw_mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1260, 21))
        self.menubar.setObjectName("menubar")
        mw_mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=mw_mainWindow)
        self.statusbar.setObjectName("statusbar")
        mw_mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mw_mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mw_mainWindow)

    def retranslateUi(self, mw_mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mw_mainWindow.setWindowTitle(_translate("mw_mainWindow", "MainWindow"))
        self.gb_node.setTitle(_translate("mw_mainWindow", "Редактор узлов"))
        self.pb_main_addNode.setText(_translate("mw_mainWindow", "Добавить узел"))
        self.pb_main_changeNode.setText(_translate("mw_mainWindow", "Изменить узел"))
        self.pb_main_deleteNode.setText(_translate("mw_mainWindow", "Удалить узел"))
        self.gb_connection.setTitle(_translate("mw_mainWindow", "Редактор каналов"))
        self.pb_main_addConnection.setText(_translate("mw_mainWindow", "Добавить/удалить канал"))
        self.gb_matrix.setTitle(_translate("mw_mainWindow", "Матрицы"))
        self.pb_main_adjacencyMatrix.setText(_translate("mw_mainWindow", "Матрица смежности"))
        self.pb_main_incidenceMatrix.setText(_translate("mw_mainWindow", "Матрица инцидентности"))
        self.pb_main_loadMatrix.setText(_translate("mw_mainWindow", "Матрица нагрузки"))
        self.pb_shortestPath.setText(_translate("mw_mainWindow", "Отобразить\n"
"кратчайшие пути"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mw_mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mw_mainWindow()
    ui.setupUi(mw_mainWindow)
    mw_mainWindow.show()
    sys.exit(app.exec())
