# Form implementation generated from reading ui file 'shortest_path.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_d_shortestWaysWindow(object):
    def setupUi(self, d_shortestWaysWindow):
        d_shortestWaysWindow.setObjectName("d_shortestWaysWindow")
        d_shortestWaysWindow.resize(651, 601)
        self.tw_shortestPath = QtWidgets.QTableWidget(parent=d_shortestWaysWindow)
        self.tw_shortestPath.setGeometry(QtCore.QRect(0, 0, 651, 601))
        self.tw_shortestPath.setObjectName("tw_shortestPath")
        self.tw_shortestPath.setColumnCount(0)
        self.tw_shortestPath.setRowCount(0)

        self.retranslateUi(d_shortestWaysWindow)
        QtCore.QMetaObject.connectSlotsByName(d_shortestWaysWindow)

    def retranslateUi(self, d_shortestWaysWindow):
        _translate = QtCore.QCoreApplication.translate
        d_shortestWaysWindow.setWindowTitle(_translate("d_shortestWaysWindow", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    d_shortestWaysWindow = QtWidgets.QDialog()
    ui = Ui_d_shortestWaysWindow()
    ui.setupUi(d_shortestWaysWindow)
    d_shortestWaysWindow.show()
    sys.exit(app.exec())
